#pragma once

//
//// VCU IDs
#define ID_VCU_STATUS 0xC3
#define ID_VCU_PEDAL_READINGS 0xC4
#define ID_VCU_WS_READINGS 0xC6
#define ID_VCU_PEDAL_THRESHOLD_SETTINGS 0xC7
#define ID_VCU_FW_VERSION 0xC8
#define ID_VCU_BOARD_ANALOG_READS_ONE 0xC9
#define ID_VCU_BOARD_ANALOG_READS_TWO 0xCA
#define ID_VCU_PEDAL_TRAVEL 0xCC

// number of rx and tx mailboxes
//  TODO: Make this gone
#define NUM_TX_MAILBOXES 32
#define NUM_RX_MAILBOXES 32

//
//// BMS IDs
#define ID_BMS_SOC 0x6B3
#define ID_BMS_CURRENT_LIMIT_INFO 0x6B1
#define ID_BMS_PACK_VOLTAGE_INFO 0x6B2

//
//// TCU IDs
#define ID_PRECHARGE_STATUS 0x69

//
//// MDB IDs
#define ID_MODULE_1_A 0x1F
#define ID_MODULE_1_B 0x29

#define ID_MODULE_2_A 0x20
#define ID_MODULE_2_B 0x2A

#define ID_MODULE_3_A 0x21
#define ID_MODULE_3_B 0x2B

#define ID_MODULE_4_A 0x22
#define ID_MODULE_4_B 0x2C

#define ID_MODULE_5_A 0x23
#define ID_MODULE_5_B 0x2D

//
//// 8CU IDs
#define ID_ACU_READINGS 0x259
#define ID_ACU_STATUS 0x25A
#define ID_ACU_SHUTDOWN_DATA 0x25B

//
//// Inverter IDs
#define ID_MC_CURRENT_LIMIT_COMMAND 0x202
#define ID_MC_TEMPERATURES_1 0xA0
#define ID_MC_TEMPERATURES_2 0xA1
#define ID_MC_TEMPERATURES_3 0xA2
#define ID_MC_ANALOG_INPUTS_VOLTAGES 0xA3
#define ID_MC_DIGITAL_INPUT_STATUS 0xA4
#define ID_MC_MOTOR_POSITION_INFORMATION 0xA5
#define ID_MC_CURRENT_INFORMATION 0xA6
#define ID_MC_VOLTAGE_INFORMATION 0xA7
#define ID_MC_FLUX_INFORMATION 0xA8
#define ID_MC_INTERNAL_VOLTAGES 0xA9
#define ID_MC_INTERNAL_STATES 0xAA
#define ID_MC_FAULT_CODES 0xAB
#define ID_MC_TORQUE_TIMER_INFORMATION 0xAC
#define ID_MC_MODULATION_INDEX_FLUX_WEAKENING_OUTPUT_INFORMATION 0xAD
#define ID_MC_FIRMWARE_INFORMATION 0xAE
#define ID_MC_DIAGNOSTIC_DATA 0xAF
#define ID_MC_COMMAND_MESSAGE 0xC0
#define ID_MC_READ_WRITE_PARAMETER_COMMAND 0xC1
#define ID_MC_READ_WRITE_PARAMETER_RESPONSE 0xC2

//
//// Dash IDs
#define ID_DASH_BUTTONS 0xEB
#define ID_DASH_FW_VERSION 0xEC

//
//// Evelogger IDs
#define ID_NAV_TIME 0X1F4
#define ID_NAV_POSITION 0X1F7
#define ID_NAV_ATTITUDE 0X1F5
#define ID_NAV_GYRO 0X1F6
#define ID_NAV_VELOCITY 0X1F8
#define ID_NAV_ACCEL 0X1F9
